LANGUAGE_CONFIGS = {
    "fr": {
        "name": "French",
        "section_marker": "section",
        "section_format": "both",
        "sections": {
            "1": ["un", "1", "a"],
            "2": ["deux", "2", "b"],
            "3": ["trois", "3", "c"],
            "4": ["quatre", "4", "d"],
            "5": ["cinq", "5", "e"],
        },
    },
    "de": {
        "name": "German",
        "section_marker": "fragen zu teil",
        "section_format": "number",
        "sections": {
            "1": ["eins", "1"],
            "2": ["zwei", "2"],
            "3": ["drei", "3"],
            "4": ["vier", "4"],
            "5": ["fünf", "5"],
        },
    },
    "es": {
        "name": "Spanish",
        "section_marker": "número",
        "section_format": "number",
        "sections": {
            "1": ["uno", "1", "primera"],
            "2": ["dos", "2", "segunda"],
            "3": ["tres", "3", "tercera"],
            "4": ["cuatro", "4", "cuarta"],
            "5": ["cinco", "5", "quinta"],
            "6": ["seis", "6", "sexta"],
            "7": ["siete", "7", "séptima"],
        },
    },
    "zh": {
        "name": "Chinese",
        "section_marker": "请看问题",
        "section_format": "sequential",
        "sections": {
            "1": ["A", "a", "一"],
            "2": ["B", "b", "二"],
            "3": ["C", "c", "三"],
            "4": ["D", "d", "四"],
            "5": ["E", "e", "五"],
            "6": ["F", "f", "六"],
        },
    },
    "ga": {
        "name": "Irish",
        "section_marker": "cuid",
        "section_format": "number",
        "sections": {
            "1": ["aon", "1", "a"],
            "2": ["dó", "2", "b"],
            "3": ["trí", "3", "c"],
            "4": ["ceathair", "4", "d"],
            "5": ["cúig", "5", "e"],
        },
    },
    "it": {
        "name": "Italian",
        "section_marker": "sezione",
        "section_format": "both",
        "sections": {
            "1": ["uno", "1", "a"],
            "2": ["due", "2", "b"],
            "3": ["tre", "3", "c"],
            "4": ["quattro", "4", "d"],
            "5": ["cinque", "5", "e"],
        },
    },
}
